apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
    - port:
        - ports: 3306
          targetPort: vprodb-pory
          protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP